# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ["__main__.py"],
    pathex=[],
    binaries=[],
    datas=[
        ("skills", "skills"),
        ("prompt_modules", "prompt_modules"),
        ("internal/plugins", "internal/plugins"),
        ("config.example.json", "."),
        ("config.example-prompt-modules.json", "."),
        ("README.md", "."),
        ("USER_GUIDE.md", "."),
    ],
    hiddenimports=[
        # PySide6
        "PySide6",
        "PySide6.QtCore",
        "PySide6.QtGui",
        "PySide6.QtMultimedia",
        "PySide6.QtWidgets",
        # Agent core
        "internal.agent.agent",
        "internal.agent.register",
        "internal.agent.bubble_timing",
        "internal.agent.chat_service",
        "internal.agent.tool_setup",
        "internal.agent.voice",
        "internal.agent.agent_support.ollama",
        "internal.agent.agent_support.online",
        "internal.agent.agent_support.transformers",
        # Agent sandbox & planning
        "internal.agent.sandbox",
        "internal.agent.planning",
        "internal.agent.planning.storage",
        # Agent tools
        "internal.agent.tool.base",
        "internal.agent.tool.file",
        "internal.agent.tool.office",
        "internal.agent.tool.web_search",
        "internal.agent.tool.live2d.clear_expression",
        "internal.agent.tool.live2d.display_bubble_text",
        "internal.agent.tool.live2d.next_expression",
        "internal.agent.tool.live2d.play_sound",
        "internal.agent.tool.live2d.set_background",
        "internal.agent.tool.live2d.set_expression",
        "internal.agent.tool.live2d.set_model",
        "internal.agent.tool.live2d.trigger_motion",
        "internal.agent.tool.meta.delete_tool",
        "internal.agent.tool.meta.generate_tool",
        "internal.agent.tool.meta.list_tools",
        "internal.agent.tool.meta.rollback_tool",
        "internal.agent.tool.dynamic",
        "internal.agent.tool.dynamic.storage",
        "internal.agent.tool.dynamic.tools",
        # Config
        "internal.config.config",
        # Memory
        "internal.memory",
        "internal.memory.storage",
        # MCP
        "internal.mcp",
        "internal.mcp.protocol",
        "internal.mcp.config",
        "internal.mcp.manager",
        "internal.mcp.compression",
        "internal.mcp.backend",
        "internal.mcp.remote",
        # RAG
        "internal.rag",
        "internal.rag.document",
        "internal.rag.embeddings",
        "internal.rag.index",
        # Cordis kernel and application plugins
        "internal.cordis",
        "internal.cordis.context",
        "internal.cordis.errors",
        "internal.cordis.events",
        "internal.cordis.lifecycle",
        "internal.cordis.loader",
        "internal.cordis.logger",
        "internal.cordis.plugin",
        "internal.cordis.registry",
        "internal.cordis.schema",
        "internal.cordis.timer",
        "internal.plugins",
        "internal.plugins.app",
        "internal.plugins.agent.loop",
        "internal.plugins.agent.loop_minimal",
        "internal.plugins.agent.model",
        "internal.plugins.core.config",
        "internal.plugins.core.logger",
        "internal.plugins.core.mcp",
        "internal.plugins.core.memory",
        "internal.plugins.core.planner",
        "internal.plugins.core.prompts",
        "internal.plugins.core.rag",
        "internal.plugins.core.sandbox",
        "internal.plugins.core.scheduler",
        "internal.plugins.core.session",
        "internal.plugins.core.skills",
        "internal.plugins.core.timer",
        "internal.plugins.core.tools",
        "internal.plugins.core.web",
        "internal.plugins.integration.browser",
        "internal.plugins.integration.clipboard",
        "internal.plugins.integration.hotkey",
        "internal.plugins.meta.diagnostics",
        "internal.plugins.meta.evolution_store",
        "internal.plugins.meta.evolution_tools",
        "internal.plugins.meta.hmr",
        "internal.plugins.meta.plugin_sandbox",
        "internal.plugins.meta.plugin_templates",
        "internal.plugins.meta.self_evolution",
        "internal.plugins.outputs.plain",
        "internal.plugins.outputs.typewriter",
        "internal.plugins.ui.bubble_widget",
        "internal.plugins.ui.chat_history",
        "internal.plugins.ui.input_box",
        "internal.plugins.ui.settings",
        "internal.plugins.ui.tray",
        # Skill
        "internal.skill",
        "internal.skill.builtin",
        # UI
        "internal.ui",
        "internal.ui.input_box",
        "internal.ui.bubble_widget",
        "internal.ui.title_bar",
        "internal.ui.settings_window",
        "internal.ui.chat_history_window",
        "internal.ui.styles",
        "internal.ui.history_manager",
        "internal.ui.markdown_renderer",
        # App
        "internal.app.bootstrap",
        "internal.app.live2d_agent_app",
        "internal.app.runtime",
        "internal.app.tray",
        "internal.app.smoke_bridge",
        # WebSocket
        "internal.websocket.client",
        "internal.websocket.reconnect",
        # Prompt manager
        "internal.prompt_manager",
        # Integration
        "internal.integration.hotkey",
        "internal.integration.clipboard",
        # Scheduler
        "internal.scheduler",
        # Session
        "internal.session",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=["numpy.distutils.tests", "pytest", "tests", "test", "ruff", "poetry"],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name="live2d-agent",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
