[mypy]
python_version = 3.14
pretty = True
show_error_codes = True
ignore_missing_imports = True
follow_imports = silent
namespace_packages = True
explicit_package_bases = True
disable_error_code = import-untyped, annotation-unchecked
exclude = (?x)(^tests/planning/test_integration\.py$)

[mypy-internal.websocket.client]
ignore_errors = True
