[pytest]
testpaths = test
python_files = test_*.py
addopts =
    --ignore=test/planning/test_integration.py
norecursedirs =
    .git
    .github
    .pytest_cache
    .ruff_cache
    .mypy_cache
    .venv
    build
    dist
    data
