"""Example: Data Processing Tool

Demonstrates a dynamic tool that processes data using multiple allowed modules.
This example shows statistical calculation with multiple imports.
"""

import statistics
from collections import Counter

from internal.agent.tool.base import Tool

class StatisticsCalculatorTool(Tool):
    """Calculate basic statistics from a list of numbers."""

    @property
    def name(self) -> str:
        return "calculate_statistics"

    @property
    def description(self) -> str:
        return "Calculate basic statistical measures (mean, median, mode, stddev, min, max) from a list of numbers."

    @property
    def parameters(self) -> dict:
        return {
            "type": "object",
            "properties": {
                "numbers": {
                    "type": "array",
                    "items": {"type": "number"},
                    "description": "List of numbers to analyze",
                },
            },
            "required": ["numbers"],
        }

    async def execute(self, numbers: list[float]) -> dict:
        """Calculate statistics and return results as a dictionary."""
        if not numbers:
            return {
                "error": "Empty list provided",
                "count": 0,
            }

        result = {
            "count": len(numbers),
            "min": min(numbers),
            "max": max(numbers),
            "sum": sum(numbers),
            "mean": statistics.mean(numbers),
            "median": statistics.median(numbers),
        }

        # Calculate mode - handle multiple modes
        try:
            result["mode"] = statistics.mode(numbers)
        except statistics.StatisticsError:
            # Multiple modes - get all unique values with counts
            counter = Counter(numbers)
            max_count = max(counter.values())
            modes = [k for k, v in counter.items() if v == max_count]
            result["mode"] = modes
            result["has_multiple_modes"] = len(modes) > 1

        # Calculate standard deviation if we have more than one number
        if len(numbers) > 1:
            result["stddev"] = statistics.stdev(numbers)
            result["variance"] = statistics.variance(numbers)

        return result


# Generated by: dynamic tool generation system
# Generated at: 2026-04-11T...
