"""Example: HTTP Request Tool

Demonstrates a dynamic tool that makes HTTP requests using urllib.
This example shows how to use allowed modules to create a practical tool.
"""

# This is what the generated code would look like
# After generation, it would be saved as: {tool_name}_tool.py

import urllib.request
import urllib.parse

from internal.agent.tool.base import Tool

class HttpRequestTool(Tool):
    """Make an HTTP GET request to a URL and return the response."""

    @property
    def name(self) -> str:
        return "http_get_request"

    @property
    def description(self) -> str:
        return "Make an HTTP GET request to a given URL and return the response text. Only works with http:// and https:// URLs that allow anonymous access."

    @property
    def parameters(self) -> dict:
        return {
            "type": "object",
            "properties": {
                "url": {
                    "type": "string",
                    "description": "The URL to request",
                },
            },
            "required": ["url"],
        }

    async def execute(self, url: str) -> str:
        """Make HTTP GET request and return response."""
        try:
            with urllib.request.urlopen(url, timeout=10) as response:
                content = response.read().decode('utf-8')
                # Return first 2000 characters to avoid huge responses
                if len(content) > 2000:
                    content = content[:2000] + "\n... (truncated)"
                return content
        except Exception as e:
            return f"Error making request: {str(e)}"


# Generated by: dynamic tool generation system
# Generated at: 2026-04-11T...
