"""Example: System Information Query Tool

Demonstrates a dynamic tool that gets system information using allowed modules.
Note: This tool doesn't access the file system or network, just gets
basic information that's already available through standard modules.
"""

import platform
import math
from datetime import datetime

from internal.agent.tool.base import Tool

class SystemInfoTool(Tool):
    """Get basic system information including OS, Python version, and current time."""

    @property
    def name(self) -> str:
        return "get_system_info"

    @property
    def description(self) -> str:
        return "Get basic system information including OS name, Python version, architecture, and current datetime."

    @property
    def parameters(self) -> dict:
        return {
            "type": "object",
            "properties": {},
            "required": [],
        }

    async def execute(self) -> dict:
        """Get system information and return as dictionary."""
        info = {
            "os_name": platform.system(),
            "os_release": platform.release(),
            "os_version": platform.version(),
            "python_implementation": platform.python_implementation(),
            "python_version": platform.python_version(),
            "architecture": platform.architecture(),
            "machine": platform.machine(),
            "processor": platform.processor(),
            "current_datetime": datetime.now().isoformat(),
        }

        # Add some computed information using math
        pi_digits = str(math.pi)
        info["pi_10_digits"] = pi_digits[:12]

        return info


# Generated by: dynamic tool generation system
# Generated at: 2026-04-11T...
